In [2]:
from pylab import *

In [8]:
a = 40e-3
k = 34e-3/0.4e-9
I = np.arange(0, 100e-3, 10e-3)
mu_0 = 4*pi*1e-7
N = 1000
B = mu_0*N*I/(2*pi*a)

V = np.array([2.40, 5.69, 15.01, 18.04, 17.38, 26.72, 31.39, 35.57, 35.00])*1e-3

In [9]:
I

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [13]:
B*(I/0.01 + 1/40.0)

array([0.00000e+00, 5.12500e-05, 2.02500e-04, 4.53750e-04, 8.05000e-04,
       1.25625e-03, 1.80750e-03, 2.45875e-03, 3.21000e-03, 4.06125e-03])

In [14]:
B

array([0.0e+00, 5.0e-05, 1.0e-04, 1.5e-04, 2.0e-04, 2.5e-04, 3.0e-04,
       3.5e-04, 4.0e-04, 4.5e-04])

In [21]:
(0.001/I[1:] + 1/40) * 100

array([12.5       ,  7.5       ,  5.83333333,  5.        ,  4.5       ,
        4.16666667,  3.92857143,  3.75      ,  3.61111111])