In [2]:
from pylab import *

In [26]:
a = 40e-3
k = 34e-3/0.4e-9
I = np.arange(0, 100e-3, 10e-3)
mu_0 = 4*pi*1e-7
N = 1000
B = mu_0*N*I/(2*pi*a)

V = np.array([0, 2.40, 5.69, 15.01, 18.04, 17.38, 26.72, 31.39, 35.57, 35.00])*1e-3

In [34]:
V

array([0.     , 0.0024 , 0.00569, 0.01501, 0.01804, 0.01738, 0.02672,
       0.03139, 0.03557, 0.035  ])

In [13]:
B*(I/0.01 + 1/40.0)

array([0.00000e+00, 5.12500e-05, 2.02500e-04, 4.53750e-04, 8.05000e-04,
       1.25625e-03, 1.80750e-03, 2.45875e-03, 3.21000e-03, 4.06125e-03])

In [39]:
sum(B*V)/(sum(V*V)) / (1e-6/1e-3)

11.78515888017646

array([0.     , 0.0024 , 0.00569, 0.01501, 0.01804, 0.01738, 0.02672,
       0.03139, 0.03557, 0.035  ])