In [2]:
from pylab import *

In [40]:
a = 40e-3
k = 34e-3/0.4e-9
I = np.arange(0, 100e-3, 10e-3)
mu_0 = 4*pi*1e-7
B = mu_0*I/(2*pi*a)
V = k*B
V + noise

array([ 1.03159116,  2.40350195,  5.69217289, 15.00957449, 18.04028726,
       17.38543638, 26.72544903, 31.39146485, 35.57297147, 35.00517367])

In [16]:
I

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [28]:
noise = np.random.normal(0,2,10)
noise

array([ 1.03159116, -1.84649805, -2.80782711,  2.25957449,  1.04028726,
       -3.86456362,  1.22544903,  1.64146485,  1.57297147, -3.24482633])